name: push_master
on:
  push:
    branches:
      - 'master'

jobs:
  apply:
    name: Apply
    strategy:
      matrix:
        module_name: [ master-user, cloud9 ]
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:1.0.4
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.FORMIT_MASTER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.FORMIT_MASTER_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-1"
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ENVIRONMENT_NAME: prod
    steps:
      - uses: actions/checkout@v2
      - run: terragrunt apply --terragrunt-working-dir "$GITHUB_WORKSPACE/deploy/master-user" -input=false -auto-approve
