name: push_master
on:
  push:
    branches:
      - 'master'

jobs:
  plan:
    name: Plan
    strategy:
      matrix:
        module_name: [ master-user ]
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:1.0.4
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.FORMIT_MASTER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.FORMIT_MASTER_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-1"
        ENVIRONMENT_NAME: prod
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/${{ matrix.module_name }}/plan.sh
      - uses: actions/upload-artifact@v2
        with:
          name: plan
          path: out/*.tfplan
  apply:
    name: Apply
    needs: plan
    strategy:
      matrix:
        module_name: [ master-user ]
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:1.0.4
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.FORMIT_MASTER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.FORMIT_MASTER_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-1"
        ENVIRONMENT_NAME: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: plan
          path: out
      - run: ./scripts/${{ matrix.module_name }}/apply-plan.sh
